Update org logo API
ECellNitrr/teesco-backend pull request #116
Opened 2020-06-04 04:20 UTC by akhil-maker

### Fixes #66 

### Description
I have added a PUT API to update the profile-pic of an organisation. Only test cases are not provided for this pr.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested locally with the help of postman 

When all details provided by an authenticated and authorized user who is the admin of the organisation.
![IMG_20200604_093122](https://user-images.githubusercontent.com/58397226/83714021-3cbb0600-a647-11ea-9be2-62c026ea05d0.jpg)

It will provide following response when authentication details are not provided.
![IMG_20200604_092851](https://user-images.githubusercontent.com/58397226/83714155-9cb1ac80-a647-11ea-876b-e4c495418563.jpg)

When the organisation is deleted or not present, it will show the following response
![IMG_20200604_092729](https://user-images.githubusercontent.com/58397226/83714350-1fd30280-a648-11ea-8a82-b1dcf657171a.jpg)

### Checklist:
- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [X] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [X] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-06-04 04:26 UTC, sahil9001 commented
Few changes required,
1. Add test cases (without them we can't merge)
2. Make a new branch for the issue, we don't merge `dev` branch of your fork.
3. Resolve conflicts.

2020-06-04 05:04 UTC, sahil9001 requested changes

2020-06-04 05:04 UTC, sahil9001 commented on org/urls.py
> +    path('<int:org_id>/', put_pic),
This should be `<int:org_id>/profile_pic/` I guess.

2020-06-04 05:04 UTC, sahil9001 commented on org/serializers.py
> +class picserializer(serializers.ModelSerializer):
Naming of serializers should be proper.

2020-06-04 05:04 UTC, sahil9001 commented on org/responses.py
> +}
I see some repeated responses here, please remove them.

2020-06-04 07:34 UTC, naveennvrgup commented
> 1. Add test cases (without them we can't merge)
1. Please add a folder PROJECT_ROOT/assets/test/
1. Add a pic over there
1. and try to send that pic while making the testing
1. testing is crucial as @sahil9001 told
> 2. Make a new branch for the issue, we don't merge `dev` branch of your fork.
> 3. Resolve conflicts.
> 4. Rebase or either pull the upstream `dev` to fetch latest changes.

(2-4)absolutely. I recommend `pull the upstream dev to feature branch`  for beginners.

2020-06-04 14:14 UTC, anshsrtv requested changes
Wasn't hoping for this PR, so Kudos :tada:, you made the PR . But surely a lot of work left...

1. The responses aren't proper, the API gives `"Organization details updated successfully"` everytime an admin makes a request.
2. Check if the API works properly using the admin panel.
4. Hope the testcases arrive soon :v:

2020-06-04 14:14 UTC, anshsrtv commented on org/views.py
> +    if isadmin % 2 == 1:
@akhil-maker Please explain the condition.. I didn't get your way of checking whether the user is an Admin

2020-06-04 14:14 UTC, anshsrtv commented on org/views.py
> +        if request.method == "PUT":
I don't think there's any need for checking whether the method is `PUT`. It's already taken care of by the `@api_view(['PUT'])` .

2020-06-04 14:14 UTC, anshsrtv commented on org/views.py
> +        else:
A mistake, check the indentation.

2020-06-04 14:14 UTC, anshsrtv commented on org/serializers.py
> +class picserializer(serializers.ModelSerializer):
Try naming variables the way we usually name them.. looks good that way :wink:

2020-06-05 05:04 UTC, akhil-maker commented on org/serializers.py
> +class picserializer(serializers.ModelSerializer):
Ok @sahil9001 @anshsrtv

2020-06-05 05:06 UTC, akhil-maker commented on org/views.py
> +        else:
I will correct it @anshsrtv

2020-06-05 05:06 UTC, closed without merging