Forget passward
ECellNitrr/teesco-backend pull request #124
Opened 2020-06-05 13:22 UTC by anshsrtv

### Fixes #109 

### Description
The forget password API is ready and tested with relevant testcases

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- Documentation

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (`MOCK_EMAIL = True` and printing body in mock email)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
This has been tested using the django test cases and using swagger docs.
```
ansh@ansh-HP-Notebook:~/Desktop/teesco-backend$ python manage.py test 
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..........................................................
----------------------------------------------------------------------
Ran 58 tests in 18.130s

OK
Destroying test database for alias 'default'...
```

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2020-06-06 18:34 UTC, naveennvrgup requested changes
1. Please revert changes made to `org/responses.py`
1. Great quality code. appreciate the efforts you made for documentation :clap: :medal_military:

2020-06-06 18:34 UTC, naveennvrgup commented on users/views.py
> +                E-Cell NITRR Open Source"
```suggestion
                Teesco (Volunteer Management System)"
```

2020-06-06 18:34 UTC, naveennvrgup commented
Tested locally works great :+1:

2020-06-07 06:19 UTC, anshsrtv commented
> 1. Please revert changes made to `org/responses.py`
> 2. Great quality code. appreciate the efforts you made for documentation clap medal_military
Made the changes :v:

2020-06-08 19:37 UTC, priyanshisharma approved these changes
Tested it locally, Looks right! 🎉

2020-06-10 14:09 UTC, sahil9001 requested changes

2020-06-10 14:09 UTC, sahil9001 commented on utils/email_service.py
> +                raise ValueError("Invalid Gmail credentials!")
`email_service.py` was already added in the previous PR. :sweat_smile:

2020-06-11 09:23 UTC, naveennvrgup approved these changes
1. Tested locally works as expected.
1. Great quality code :clap:

2020-06-11 09:23 UTC, merged