feat: Added org info API
ECellNitrr/teesco-backend pull request #127
Opened 2020-06-07 07:55 UTC by sahil9001

### Fixes #120 

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
This commit adds the functionality to fetch the information about any
organisation by an authorised user, so that users can check the details
before joining them.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
```
(envteesco) sahil@laptop:~/Desktop/Projects/teesco-backend$ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..........................................................
----------------------------------------------------------------------
Ran 58 tests in 11.920s
```

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-06-11 05:23 UTC, anshsrtv reviewed
Nicely done @sahil9001 :rocket: ... I have commented on some parts of code.. Please check them.

2020-06-11 05:23 UTC, anshsrtv commented on org/urls.py
> -    path('<int:org_id>/group/', GetGroup, name='get_group'),
Remove the add_volunteer URL ... It has been repeated two times

2020-06-11 05:23 UTC, anshsrtv commented on org/views.py
> +            '403': set_example(responses.user_unauthorized_403),
It Should be  `401 Unauthorized` in place of 403.

2020-06-15 05:02 UTC, sahil9001 commented
@naveennvrgup Can we merge this now?

2020-06-15 10:04 UTC, naveennvrgup requested changes
1. Nice test cases :fire: 
1. Please fix conflicts

2020-06-15 10:04 UTC, naveennvrgup commented on org/views.py
> +        response_body = [{
```suggestion
        response_body = {
```

2020-06-15 10:04 UTC, naveennvrgup commented on org/views.py
> +        }]
```suggestion
        }
```

2020-06-15 10:04 UTC, naveennvrgup commented on org/views.py
> +            "cover_pic": org.cover_pic if org.cover_pic else None
```suggestion
            "profile_pic": request.build_absolute_uri(org.profile_pic.url) if org.profile_pic else None,
            "cover_pic": request.build_absolute_uri(org.cover_pic.url) if org.cover_pic else None
```

2020-06-22 07:01 UTC, naveennvrgup approved these changes
1. Great job @sahil9001 
1. tested locally works as expected

2020-06-22 07:01 UTC, merged