Custom Permission Field
ECellNitrr/teesco-backend pull request #42
Opened 2020-04-29 12:07 UTC by naveennvrgup

### Fixes #29

### Description
1. Created PermissionSet class
1. Created PermissionField class
1. Added tests for both classes
1. Added migrations for PermissionSetTestModel
1. Verified proper functioning of PermissionField

**Credits:**
1. @BadduCoder - suggested the idea of using bit-manipulation instead of using string
1. @priyanshisharma - for efforts in #40 
1. @sahil9001  - for efforts in #39 

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- Documentation

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

**Code/Quality Assurance**
- [X] My changes generate no new warnings 
- [X] I have added tests that prove my fix is effective or that my feature works

2020-04-29 12:10 UTC, naveennvrgup commented
@priyanshisharma  @sahil9001 Please go through this PR and check for error. You both made great efforts for #42 . :+1:

2020-04-29 12:13 UTC, naveennvrgup reviewed
The tests are moved to a common test folder.

2020-05-04 16:41 UTC, sumit-badsara requested changes
Suggestion to improve readability of code ! Other things which I suggested (Using loops instead of hard coding) can be improved later on as an improvement PR.

2020-05-04 16:41 UTC, BadduCoder commented on tests/utils/tests_permission_field.py
> +        p_one = 1 << PermissionSet.IS_ADMIN
Better to name the variables as permission name or something related.

2020-05-04 16:47 UTC, sumit-badsara approved these changes

2020-05-04 16:48 UTC, merged