Added swagger doc (Removed all suggested errors)
ECellNitrr/teesco-backend pull request #46
Opened 2020-04-30 12:19 UTC by KunalAnkur

### Fixes issue #8 

### Description
By fixing this issue I have used drf-yasg package in which we can only interact via swagger user interface. And removed all the error that @naveennvrgup sir have suggested.

**Type of Change:** (Delete irrelevant options)
- Code

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
You can test just by running python manage.py runserver after installing all the requirements.
till now there is no API in the app so we can just see the UI of swagger doc at http://localhost:8000/swagger url.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-05-04 16:52 UTC, sumit-badsara requested changes
Good work @KunalAnkur ! Just a minor change.

2020-05-04 16:52 UTC, BadduCoder commented on server/urls.py
> +      terms_of_service="https://https://ecell.nitrr.ac.in/terms",
remove one https://

2020-05-04 16:54 UTC, BadduCoder commented
Closed #41 , As this PR is more recent and updated.

2020-05-04 17:01 UTC, BadduCoder commented
@KunalAnkur Don't mention comments in PR title. 
Removed **Removed all suggested errors** from title.

2020-05-08 11:28 UTC, naveennvrgup commented
1. Since no response from @KunalAnkur  for 4 days I am reassigning this PR to @sahil9001. 
1. @sahil9001  Please take this PR and resolve the conflicts
1. And address the comments made by @BadduCoder @naveennvrgup

2020-05-08 11:29 UTC, closed without merging